title: Programació Icària. Receptari Pyton
description: Petites receptes de codi en Pyhton per a la matèria Programació de 1r de batxillerat a l'institut Icària de Barcelona.
theme: just-the-docs

url: https://prgicaria.github.io/receptari/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
