title: PRG Icària. Receptari Python
description: Petites receptes de codi en Pyhton per a la matèria Programació de 1r de batxillerat a l'institut Icària de Barcelona.
theme: just-the-docs

url: https://prgicaria.github.io/receptari/
# logo: "/imatges/Icaria.png"
favicon_ico: "/imatges/favicon.ico"

aux_links:
  GitHub Repositori: https://github.com/prgicaria/receptari
