title: PRG Icària. Receptari Python
description: Petites receptes de codi en Pyhton per a la matèria Programació de 1r de batxillerat a l'institut Icària de Barcelona.
theme: just-the-docs

url: https://prgicaria.github.io/receptari/
# logo: "/imatges/Icaria.png"
favicon_ico: "/imatges/favicon.ico"

aux_links:
  GitHub Repositori: https://github.com/prgicaria/receptari

# External navigation links
nav_external_links:
  - title: Curs de programació al Moodle de l'institut Icària
    url: https://educaciodigital.cat/iesicaria/moodle/course/view.php?id=2705
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
